// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc27.Robot.subsystems;

import org.usfirst.frc27.Robot.Robot;
import org.usfirst.frc27.Robot.RobotMap;
import org.usfirst.frc27.Robot.commands.*;
import org.usfirst.frc27.Robot.commands.DriveTrain.DriveWithJoysticks;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Joystick.AxisType;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Arm extends Subsystem {

   
    private final CANTalon arm = RobotMap.arm;
 
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
      
        // Set the default command for a subsystem here.
        setDefaultCommand(new ActivateArm());
    }

    public void armOn() {
    	arm.set(Robot.oi.rightJoystick.getAxis(AxisType.kZ));    
    	SmartDashboard.putNumber("Arm", 1);
    }

    public void armOff() {
    	arm.set(0);
    }

}

