// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc27.Robot.subsystems;

import org.usfirst.frc27.Robot.RobotMap;
import org.usfirst.frc27.Robot.commands.*;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class BallDelivery extends Subsystem {

   
    private final DoubleSolenoid ballDelivery1 = RobotMap.ballDeliveryBallDelivery1;
    //private final DoubleSolenoid ballDelivery2 = RobotMap.ballDeliveryBallDelivery2;
    //private final DoubleSolenoid ballDelivery3 = RobotMap.ballDeliveryBallDelivery3;

   


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
      

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void extend() {
    	ballDelivery1.set(Value.kForward);
    }

    public void retract() {
    	ballDelivery1.set(Value.kReverse);
    }
    
}

