// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc27.Robot.subsystems;

import org.usfirst.frc27.Robot.RobotMap;
import org.usfirst.frc27.Robot.commands.*;
import org.usfirst.frc27.Robot.commands.DriveTrain.Drive;
import org.usfirst.frc27.Robot.commands.DriveTrain.DriveWithJoysticks;
import org.usfirst.frc27.Robot.commands.DriveTrain.Turn;

import com.kauailabs.navx.frc.AHRS;

import org.usfirst.frc27.Robot.Robot;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CANTalon.TalonControlMode;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.Joystick.AxisType;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class DriveTrain extends PIDSubsystem {

    private final CANTalon _leftMaster = RobotMap.driveTrainLeftMotor1;
    private final CANTalon _leftSlave1 = RobotMap.driveTrainLeftMotor2;
    private final CANTalon _leftSlave2 = RobotMap.driveTrainLeftMotor3;
    private final CANTalon _rightMaster = RobotMap.driveTrainRightMotor1;
    private final CANTalon _rightSlave1 = RobotMap.driveTrainRightMotor2;
    private final CANTalon _rightSlave2 = RobotMap.driveTrainRightMotor3;

    private final RobotDrive robotDrive;  

	double sensitivity = 0.5;
	
	private AHRS ahrs;

	//The turnController will use the NavX board (via ahrs object) as input.
	//It will also use the built-in PIDController that comes with the PIDSubsyste.
	PIDController turnController;
	
	//The distanceController will use an encoder connected to the robot wheels as input.
	//PIDController distanceController = new PIDController(.03, 0, 0, );
	
    public DriveTrain()
    {
    	// super supplies the PID constants (.05, 0, 0)
    	super("DriveTrain", .005, 0, 0);
    	
    	robotDrive = new RobotDrive(_leftMaster, _rightMaster);
  
    	//Invert the appropriate controllers
    	//robotDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
    	robotDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
    	    	
    	_leftSlave1.changeControlMode(TalonControlMode.Follower);
    	_leftSlave1.set(_leftMaster.getDeviceID());
    	_leftSlave2.changeControlMode(TalonControlMode.Follower);
    	_leftSlave2.set(_leftMaster.getDeviceID());
    	_rightSlave1.changeControlMode(TalonControlMode.Follower);
    	_rightSlave1.set(_rightMaster.getDeviceID());
    	_rightSlave2.changeControlMode(TalonControlMode.Follower);
       	_rightSlave2.set(_rightMaster.getDeviceID());

       	ahrs = Robot.ahrs;
       	
       	//getPIDController() returns the PID Controller that is included with 
       	//classes that extend PIDSubsystems.
       	turnController = getPIDController();
       	turnController.disable();
       	
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void initDefaultCommand() 
    { 
	    // Set the default command for a subsystem here. 
	    setDefaultCommand(new DriveWithJoysticks()); 
    } 

    public void stop(){
    	turnController.disable();
    	robotDrive.drive(0, 0);
    }

    
    public void setSensitivity(double value){
    	sensitivity = value;
    }
    

    public double getSensitivity(){
    	return sensitivity;
    }

    
    public void takeJoystickInputs(Joystick leftJoystick, Joystick rightJoystick)
    {
    	//robotDrive.tankDrive(leftJoystick, rightJoystick);
    	SmartDashboard.putNumber("Sensitivity", 1-leftJoystick.getAxis(AxisType.kZ));
    	sensitivity = 1-leftJoystick.getAxis(AxisType.kZ);
    	robotDrive.tankDrive(leftJoystick.getAxis(AxisType.kY)*sensitivity, rightJoystick.getAxis(AxisType.kY)*sensitivity);
    }
    
        
    public void drive(double speedLeft, double speedRight) {
    	robotDrive.tankDrive(speedLeft*sensitivity, speedRight*sensitivity);
    }
    
       
    public void drive(double xSpeed, double ySpeed, double yThrottle) {
    	//myRobot.arcadeDrive(sensorIRX(ai.getVoltage(), ySpeed)*yThrottle, sensorIRY(ai.getVoltage(), xSpeed)*yThrottle, true);
    	robotDrive.arcadeDrive(ySpeed*yThrottle*sensitivity, xSpeed*yThrottle*sensitivity);
    	//System.out.println(ai.getVoltage());
    }

    public void turnToHeading(double heading) {
    	ahrs.zeroYaw();
    	turnController.setSetpoint(heading);
    	turnController.enable();
    }
    
    public void perfectDrive(double moveValue, double rotateValue){
        double leftMotorSpeed;
        double rightMotorSpeed;
    	if (moveValue > 0.0) {
            if (rotateValue > 0.0) {
                leftMotorSpeed = moveValue - rotateValue;
                rightMotorSpeed = Math.max(moveValue, rotateValue);
            } else {
                leftMotorSpeed = Math.max(moveValue, -rotateValue);
                rightMotorSpeed = moveValue + rotateValue;
            }
        } else {
            if (rotateValue > 0.0) {
                leftMotorSpeed = -Math.max(-moveValue, rotateValue);
                rightMotorSpeed = moveValue + rotateValue;
            } else {
                leftMotorSpeed = moveValue - rotateValue;
                rightMotorSpeed = -Math.max(-moveValue, -rotateValue);
            }
        }
    	
    	robotDrive.tankDrive(leftMotorSpeed*sensitivity, rightMotorSpeed*sensitivity);
    	//System.out.println("left: "+leftMotorSpeed+"--- right: "+rightMotorSpeed);
    }
    
   
    public double getRobotHeading(){
    	//return ahrs.getAngle();
    	//return ahrs.getFusedHeading();
    	//return 0;
        if (ahrs.isConnected()) {
        	return ahrs.getYaw();
        }
        else {
        	return 0;
        }
    }
    

	public void resetHeading() {
		ahrs.reset();		
	}

	public void resetYaw() {
		ahrs.zeroYaw();		
	}
	
	@Override
	protected double returnPIDInput() {
		return ahrs.getYaw();
	}

	
	@Override
	protected void usePIDOutput(double output) {
    	robotDrive.tankDrive(-output, output);
	}
}

