// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc27.Robot.subsystems;

import org.usfirst.frc27.Robot.RobotMap;
import org.usfirst.frc27.Robot.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Shooter extends Subsystem {

   
    private final CANTalon shooterWheel1 = RobotMap.shooterShooterWheel1;
    private final CANTalon shooterWheel2 = RobotMap.shooterShooterWheel2;

  


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void shooterOn(){
    	double shooterSpeed = 1;
    	shooterWheel1.set(shooterSpeed);
    	shooterWheel2.set(shooterSpeed);
    }

	public void shooterOff() {
    	double shooterSpeed = 0;
    	shooterWheel1.set(shooterSpeed);
    	shooterWheel2.set(shooterSpeed);
	}
}

