// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc27.robot.subsystems;

import org.usfirst.frc27.robot.Robot;
import org.usfirst.frc27.robot.RobotMap;
import org.usfirst.frc27.robot.commands.*;
import org.usfirst.frc27.robot.commands.DriveTrain.DriveWithJoysticks;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Joystick.AxisType;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Arm extends PIDSubsystem {
	
	private final CANTalon armMotor = RobotMap.armMotor;
	
	public Arm() {
		super("Arm", .01, 0, 0);
		getPIDController().setContinuous(false);
		setSetpoint(90);
		enable();
	}
	
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
      
        // Set the default command for a subsystem here.
        //setDefaultCommand(new ActivateArm());
    }


	@Override
	protected double returnPIDInput() {
		// TODO Auto-generated method stub
		return armMotor.getAnalogInPosition();
	}

	@Override
	protected void usePIDOutput(double output) {
		// TODO Auto-generated method stub
		armMotor.pidWrite(output);
	}

}

