// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc27.Robot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainLeftMotor1;
    public static CANTalon driveTrainLeftMotor2;
    public static CANTalon driveTrainLeftMotor3;
    public static CANTalon driveTrainRightMotor1;
    public static CANTalon driveTrainRightMotor2;
    public static CANTalon driveTrainRightMotor3;
    public static CANTalon shooterShooterWheel1;
    public static CANTalon shooterShooterWheel2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftMotor1 = new CANTalon(12);
        LiveWindow.addActuator("DriveTrain", "LeftMotor1", driveTrainLeftMotor1);
        
        driveTrainLeftMotor2 = new CANTalon(14);
        LiveWindow.addActuator("DriveTrain", "LeftMotor2", driveTrainLeftMotor2);
        
        driveTrainLeftMotor3 = new CANTalon(16);
        LiveWindow.addActuator("DriveTrain", "LeftMotor3", driveTrainLeftMotor3);
        
        driveTrainRightMotor1 = new CANTalon(11);
        LiveWindow.addActuator("DriveTrain", "RightMotor1", driveTrainRightMotor1);
        
        driveTrainRightMotor2 = new CANTalon(13);
        LiveWindow.addActuator("DriveTrain", "RightMotor2", driveTrainRightMotor2);
        
        driveTrainRightMotor3 = new CANTalon(15);
        LiveWindow.addActuator("DriveTrain", "RightMotor3", driveTrainRightMotor3);
        
        shooterShooterWheel1 = new CANTalon(20);
        LiveWindow.addActuator("Shooter", "ShooterWheel1", shooterShooterWheel1);
        
        shooterShooterWheel2 = new CANTalon(19);
        LiveWindow.addActuator("Shooter", "ShooterWheel2", shooterShooterWheel2);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
